name: tokenizers.cpp ICU
on:
  workflow_dispatch:
    inputs:
      icu_major:
        description: 'ICU Major Version'
        required: true
        type: string
      icu_minor:
        description: 'ICU Minor Version'
        required: true
        type: string
env:
  GH_TOKEN: ${{ secrets.TOKENIZERSCPP_GITHUB_TOKEN }}
jobs:
  icu:
    name: Build ICU
    runs-on: macos-14
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.1'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build ICU
        working-directory: scripts/icu/
        run: |
          ./build.sh "${{ github.event.inputs.icu_major }}-${{ github.event.inputs.icu_minor }}"
          export RELEASE_TAG="icu-${{ github.event.inputs.icu_major }}-${{ github.event.inputs.icu_minor }}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          tar -czf "android-$RELEASE_TAG.tar.gz" -C output android
          tar -czf "ios-$RELEASE_TAG.tar.gz" -C output ios
      - name: Create GitHub Release
        run: |
          gh release create $RELEASE_TAG --title "Prebuilt ICU ${{ github.event.inputs.icu_major }}.${{ github.event.inputs.icu_minor }} Binaries"
      - name: Upload GitHub Release Assets
        run: |
          gh release upload $RELEASE_TAG scripts/icu/android-$RELEASE_TAG.tar.gz --clobber
          gh release upload $RELEASE_TAG scripts/icu/ios-$RELEASE_TAG.tar.gz --clobber
