name: tokenizers.cpp CI
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
env:
  ICU_MAJOR_VERSION: 75
  ICU_MINOR_VERSION: 1
  LIBTORCH_VERSION: 2.4.0
jobs:
  ci-ubuntu:
    name: CI for Ubuntu
    runs-on: ubuntu-24.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.1'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev
          wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}%2Bcpu.zip" && unzip libtorch-cxx11-abi-shared-with-deps-${LIBTORCH_VERSION}+cpu.zip -d examples/libtorch-bert
          pip install cpplint
      - name: Run Lint
        run: cpplint --recursive include/ src/ tests/
      - name: Run Build
        run: |
          cmake -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON .
          make
      - name: Run Tests
        run: |
          ctest --output-on-failure
  ci-macos:
    name: CI for macOS
    runs-on: macos-14
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.1'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          brew install icu4c
          wget "https://download.pytorch.org/libtorch/cpu/libtorch-macos-arm64-${LIBTORCH_VERSION}.zip" && unzip libtorch-macos-arm64-${LIBTORCH_VERSION}.zip -d examples/libtorch-bert
          pip install cpplint
      - name: Run Lint
        run: cpplint --recursive include/ src/ tests/
      - name: Run Build
        run: |
          export ICU_PREFIX=$(brew --prefix icu4c)
          cmake -DICU_ROOT=$ICU_PREFIX -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON .
          make
      - name: Run Tests
        run: |
          ctest --output-on-failure
